server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/securitydb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    logintype: JSON   # 配置为用JSON的方式进行响应
  freemarker:
    cache: false    # 设置是否缓存，在开发时设置为false，因为要经常修改
    suffix: .html   # 模板文件的后缀名
    charset: UTF-8  # 编码格式
    template-loader-path: classpath:/templates/
